import { useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { useThemeStore } from '../../features/theme/themeStore';
import { useNavigate } from 'react-router-dom';
import { Activity, ArrowDownUp, ArrowRight, Bell, Bookmark, BriefcaseBusiness, Check, ChevronDown, CircleHelp, Code2, Command, Compass, ExternalLink, FileCode2, GitBranch, GitFork, GitPullRequest, Globe2, LayoutDashboard, MapPin, MessageSquare, MoreHorizontal, Moon, Plus, Search, Settings2, ShieldCheck, Sparkles, Star, TrendingUp, Users, X, Sun } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis } from 'recharts';

type Repo = { name:string; description:string; language:string; color:string; stars:number; forks:number; issues:number; updated:string; tags:string[]; pinned?:boolean; image:string; };
const repos:Repo[] = [
 {name:'orbit-ui',description:'A small, sharp component system for teams who care about the details.',language:'TypeScript',color:'#3178c6',stars:1284,forks:96,issues:8,updated:'2 hours ago',tags:['react','design-system'],pinned:true,image:'linear-gradient(135deg,#3432a8,#bd73fe)'},
 {name:'fieldnotes',description:'Turn the places you visit into a map of ideas, memories and little discoveries.',language:'TypeScript',color:'#3178c6',stars:847,forks:74,issues:12,updated:'Yesterday',tags:['next.js','maps'],pinned:true,image:'linear-gradient(135deg,#0d8f84,#81dbb0)'},
 {name:'quiet-hours',description:'A focus timer that makes space for deep work and keeps your team in sync.',language:'Python',color:'#3572a5',stars:612,forks:41,issues:4,updated:'3 days ago',tags:['fastapi','productivity'],pinned:true,image:'linear-gradient(135deg,#8f4371,#efa2ae)'},
 {name:'pixel-sorter',description:'A playful image-processing playground built for the browser.',language:'JavaScript',color:'#f1e05a',stars:390,forks:28,issues:3,updated:'1 week ago',tags:['canvas','creative-coding'],image:'linear-gradient(135deg,#bd5b22,#f3bd66)'},
 {name:'tiny-queue',description:'A resilient, zero-dependency job queue for modest workloads.',language:'Go',color:'#00add8',stars:284,forks:19,issues:6,updated:'2 weeks ago',tags:['redis','backend'],image:'linear-gradient(135deg,#176477,#56bfda)'},
 {name:'atlas-search',description:'Hybrid search experiments: lexical, semantic, and everything between.',language:'Python',color:'#3572a5',stars:198,forks:15,issues:2,updated:'Last month',tags:['embeddings','search'],image:'linear-gradient(135deg,#33634d,#9aca8d)'}
];
const activityData = Array.from({length:12},(_,i)=>({month:['Nov','Dec','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct'][i],count:[21,35,28,48,39,62,51,74,69,88,64,95][i]}));
const languages=[['TypeScript',42,'#579dff'],['Python',28,'#48c99a'],['JavaScript',18,'#e8c65d'],['Go',8,'#43c8d5'],['Other',4,'#8a8395']] as const;
function GitHubMark({size=16}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 .9a11.1 11.1 0 0 0-3.51 21.63c.56.1.76-.24.76-.54v-2.08c-3.1.68-3.76-1.32-3.76-1.32-.5-1.28-1.23-1.62-1.23-1.62-1.01-.69.08-.68.08-.68 1.12.08 1.7 1.15 1.7 1.15.99 1.69 2.6 1.2 3.23.91.1-.71.39-1.2.7-1.48-2.48-.28-5.09-1.24-5.09-5.52 0-1.22.44-2.21 1.15-2.99-.12-.28-.5-1.42.11-2.95 0 0 .94-.3 3.05 1.14a10.6 10.6 0 0 1 5.55 0c2.11-1.44 3.05-1.14 3.05-1.14.61 1.53.23 2.67.11 2.95.71.78 1.15 1.77 1.15 2.99 0 4.29-2.61 5.23-5.1 5.51.4.35.75 1.03.75 2.08v3.05c0 .3.2.65.77.54A11.1 11.1 0 0 0 12 .9Z"/></svg>}
const events=[{icon:GitPullRequest,title:'Merged pull request',detail:'feat: keyboard shortcuts for command menu',repo:'orbit-ui',time:'2h ago',tone:'mint'},{icon:GitBranch,title:'Pushed 4 commits',detail:'Refined search indexing and empty states',repo:'fieldnotes',time:'Yesterday',tone:'blue'},{icon:Star,title:'Your project reached 800 stars',detail:'fieldnotes is gaining momentum',repo:'fieldnotes',time:'2d ago',tone:'gold'},{icon:MessageSquare,title:'Started a discussion',detail:'What should v2 of the API look like?',repo:'quiet-hours',time:'4d ago',tone:'purple'}];
export function DeveloperDashboard(){
 const toggleTheme=useThemeStore(s=>s.toggleTheme), theme=useThemeStore(s=>s.theme), navigate=useNavigate();
 const [tab,setTab]=useState('Overview'),[query,setQuery]=useState(''),[language,setLanguage]=useState('All languages'),[sort,setSort]=useState('Recently updated'),[connected,setConnected]=useState(false),[notice,setNotice]=useState('');
 const shown=useMemo(()=>repos.filter(r=>(r.name+' '+r.description+' '+r.tags.join(' ')).toLowerCase().includes(query.toLowerCase())&&(language==='All languages'||r.language===language)).sort((a,b)=>sort==='Most stars'?b.stars-a.stars:0),[query,language,sort]);
 const toast=(s:string)=>{setNotice(s);window.setTimeout(()=>setNotice(''),2600)};
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><Code2 size={18}/></div><span>linkhub</span><button className="workspace"><ChevronDown size={14}/></button></div><div className="side-search"><Search size={15}/><span>Jump to...</span><kbd>⌘ K</kbd></div><nav className="main-nav">{[[LayoutDashboard,'Overview'],[Compass,'Discover'],[Users,'Network'],[BriefcaseBusiness,'Opportunities']].map(([Icon,label]:any)=><button key={label} onClick={()=>navigate(label==='Overview'?'/home':label==='Discover'?'/search':label==='Network'?'/network':'/jobs')} className={tab===label?'active':''}><Icon size={17}/>{label}{label==='Network'&&<span className="nav-count">3</span>}</button>)}</nav><div className="side-label">YOUR SPACE</div><nav className="main-nav">{[[GitHubMark,'GitHub profile'],[FileCode2,'Projects'],[Bookmark,'Saved']].map(([Icon,label]:any)=><button key={label} onClick={()=>navigate(label==='GitHub profile'?'/profile':label==='Projects'?'/projects':'/settings')} className={tab===label?'active':''}><Icon size={17}/>{label}</button>)}</nav><div className="side-label team-label">YOUR NETWORK <Plus size={13}/></div><div className="team-person"><span className="mini-avatar peach">JM</span><span>Jamie Morgan</span><span className="online"/></div><div className="team-person"><span className="mini-avatar violet">AK</span><span>Alex Kim</span></div><div className="side-bottom"><button><CircleHelp size={16}/>Help & feedback</button><button><Settings2 size={16}/>Settings</button><div className="account"><img src="https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=faces"/><div><b>Sarah Chen</b><small>Pro member</small></div><MoreHorizontal size={18}/></div></div></aside>
 <main className="main"><header className="topbar"><div className="crumb">Workspace <span>/</span> <b>{tab}</b></div><div className="top-actions"><button className="icon-button"><Command size={15}/></button><button className="icon-button" title="Toggle theme" onClick={toggleTheme}>{theme==='dark'?<Sun size={15}/>:<Moon size={15}/>}</button><button className="icon-button notification"><Bell size={16}/><i/></button><span className="top-divider"/><button className="upgrade" onClick={()=>toast('You’re already on LinkHub Pro ✨')}><Sparkles size={14}/>Upgrade</button></div></header>
 <div className="content"><div className="page-heading"><div><div className="eyebrow"><span className="pulse"/> DEVELOPER PROFILE</div><h1>Your work, <span>in the open.</span></h1><p>A living portfolio of what you build, contribute, and care about.</p></div><button className="share-button" onClick={()=>toast('Profile link copied to clipboard')}><ExternalLink size={15}/>Share profile</button></div>
 <section className="profile-card"><div className="cover"><div className="cover-grid"/><div className="cover-orbit orbit-one"/><div className="cover-orbit orbit-two"/><div className="cover-pill"><span className="green-dot"/> AVAILABLE FOR WORK</div></div><div className="profile-body"><img className="avatar" src="https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=240&h=240&fit=crop&crop=faces"/><div className="profile-info"><div className="name-line"><h2>Sarah Chen</h2><span className="verified"><ShieldCheck size={13}/> Verified</span><span className="handle">@sarahbuilds</span></div><p>Product engineer building thoughtful tools for the web. Currently making the internet feel a little more human.</p><div className="profile-meta"><span><MapPin size={14}/> San Francisco, CA</span><span><BriefcaseBusiness size={14}/> Product Engineer at <b>Vercel</b></span><span><Globe2 size={14}/> sarahchen.dev</span></div><div className="profile-links"><button onClick={()=>setConnected(v=>!v)} className={connected?'connected':'github-connect'}><GitHubMark size={15}/>{connected?'Connected as sarahbuilds':'Connect GitHub'}{connected&&<Check size={14}/>}</button><span className="social-count"><Users size={14}/> 1.2k followers</span><span className="social-count">· 420 following</span></div></div><button className="edit-button" onClick={()=>toast('Profile editor is ready to connect to your account')}><Settings2 size={15}/> Edit profile</button></div></section>
 <div className="stats-grid">{[[Activity,'Contributions this year','1,284','+18% vs last year','mint'],[TrendingUp,'Current streak','18 days','Personal best: 42 days','blue'],[Star,'GitHub stars','3,615','Across 24 repositories','gold'],[Sparkles,'Developer score','92','Top 4% this month','purple']].map(([Icon,label,value,sub,tone]:any)=><motion.div whileHover={{y:-3}} className="stat-card" key={label}><div className={'stat-icon '+tone}><Icon size={17}/></div><div className="stat-label">{label}</div><div className="stat-value">{value}</div><div className="stat-sub">{sub}</div></motion.div>)}</div>
 <div className="section-tabs">{['Overview','Repositories','Activity','About'].map(t=><button onClick={()=>setTab(t)} className={tab===t?'selected':''} key={t}>{t}{t==='Repositories'&&<span>24</span>}</button>)}<button className="tab-more"><MoreHorizontal size={18}/></button></div>
 <div className="dashboard-grid"><div className="primary-column"><section className="panel contribution-panel"><div className="panel-head"><div><h3>Contribution activity</h3><p>Small steps add up to big things.</p></div><button className="period-select">Last 12 months <ChevronDown size={14}/></button></div><div className="contrib-summary"><b>1,284 <span>contributions</span></b><span className="year-label">Oct 2025 – Oct 2026</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={activityData} margin={{top:8,right:3,left:0,bottom:0}}><defs><linearGradient id="activity" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#64d9a2" stopOpacity={.22}/><stop offset="100%" stopColor="#64d9a2" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#252932"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fill:'#737b89',fontSize:11}} dy={10}/><Tooltip contentStyle={{background:'#1a1d24',border:'1px solid #333844',borderRadius:9,color:'#fff'}}/><Area type="monotone" dataKey="count" stroke="#64d9a2" strokeWidth={2} fill="url(#activity)"/></AreaChart></ResponsiveContainer></div><div className="chart-footer"><span><i className="legend-dot"/> Daily contributions</span><span className="less">Less <i/><i/><i/><i/> More</span></div></section>
 <section className="panel repos-panel"><div className="panel-head"><div><h3>Featured repositories <span className="muted-count">6</span></h3><p>Things I’ve put into the world.</p></div><button className="text-action" onClick={()=>setTab('Repositories')}>View all <ArrowRight size={14}/></button></div><div className="repo-controls"><div className="repo-search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a repository…"/></div><select value={language} onChange={e=>setLanguage(e.target.value)}><option>All languages</option>{Array.from(new Set(repos.map(r=>r.language))).map(l=><option key={l}>{l}</option>)}</select><button className="filter-btn" onClick={()=>setSort(sort==='Most stars'?'Recently updated':'Most stars')}><ArrowDownUp size={14}/>{sort}</button></div><div className="repo-grid">{shown.slice(0,4).map((r,i)=><motion.article initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:i*.05}} className="repo-card" key={r.name}><div className="repo-art" style={{background:r.image}}><span className="art-shape"/><span className="art-shape second"/><button aria-label="Repository options"><MoreHorizontal size={16}/></button></div><div className="repo-info"><div className="repo-name-row"><h4><GitHubMark size={14}/>{r.name}</h4>{r.pinned&&<span className="pinned-label">FEATURED</span>}</div><p>{r.description}</p><div className="tag-row">{r.tags.map(t=><span key={t}>{t}</span>)}</div><div className="repo-footer"><span className="language"><i style={{background:r.color}}/>{r.language}</span><span><Star size={13}/>{r.stars.toLocaleString()}</span><span><GitFork size={13}/>{r.forks}</span><span className="repo-time">{r.updated}</span></div></div></motion.article>)}</div>{shown.length===0&&<div className="empty-state">No repositories match that search.</div>}</section>
 <section className="panel activity-panel"><div className="panel-head"><div><h3>Recent activity</h3><p>A few things happening out there.</p></div><button className="text-action" onClick={()=>setTab('Activity')}>Activity log <ArrowRight size={14}/></button></div><div className="event-list">{events.map((e,i)=><div className="event" key={i}><div className={'event-icon '+e.tone}><e.icon size={15}/></div><div className="event-copy"><b>{e.title}</b><p>{e.detail} <span>in <a>{e.repo}</a></span></p></div><time>{e.time}</time></div>)}</div></section></div>
 <aside className="right-column"><section className="panel score-panel"><div className="side-panel-title"><div><h3>Developer score</h3><p>A little signal in the noise.</p></div><button><MoreHorizontal size={17}/></button></div><div className="score-ring"><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="49" className="ring-track"/><circle cx="60" cy="60" r="49" className="ring-value"/></svg><div><b>92</b><span>EXCELLENT</span></div></div><div className="rank-row"><span>Global ranking</span><b>#2,481 <small>↑ 124</small></b></div><div className="rank-row"><span>Among your peers</span><b>Top 4%</b></div><div className="score-note"><Sparkles size={14}/><span>Your consistency is carrying your score this month.</span></div></section>
 <section className="panel languages-panel"><div className="side-panel-title"><div><h3>Languages</h3><p>Across public repositories.</p></div><button><MoreHorizontal size={17}/></button></div><div className="language-bar">{languages.map(([name,n,color])=><i key={name} style={{width:n+'%',background:color}} title={name}/>)}</div><div className="language-list">{languages.slice(0,4).map(([name,n,color])=><div className="language-row" key={name}><span><i style={{background:color}}/>{name}</span><b>{n}%</b></div>)}</div><button className="all-languages" onClick={()=>toast('Language analytics opened')}>Explore tech stack <ArrowRight size={13}/></button></section>
 <section className="panel oss-panel"><div className="side-panel-title"><div><h3>Open source</h3><p>Good work travels.</p></div><span className="level-badge"><Sparkles size={12}/> GOLD</span></div><div className="oss-stats"><div><GitPullRequest size={16}/><b>38</b><span>PRs merged</span></div><div><MessageSquare size={16}/><b>16</b><span>Issues solved</span></div></div><div className="oss-progress"><div><span>Next milestone</span><b>Platinum <span>72%</span></b></div><div className="progress-track"><i/></div></div></section>
 <section className="quote-card"><div className="quote-mark">“</div><p>Build things that make people feel <em>more capable.</em></p><span>YOUR DEVELOPER MANTRA</span><div className="quote-glow"/></section>
 <button className="recruiter-card" onClick={()=>toast('Recruiter profile preview opened')}><div className="recruiter-icon"><BriefcaseBusiness size={16}/></div><div><b>Recruiter view</b><span>See your profile at a glance</span></div><ArrowRight size={15}/></button>
 </aside></div>
 <footer><span>Made with care at LinkHub</span><span>Synced 8 minutes ago <i className="sync-dot"/></span></footer></div></main><nav className="dashboard-mobile-nav"><button onClick={()=>navigate('/home')}><LayoutDashboard size={17}/><small>Home</small></button><button onClick={()=>navigate('/network')}><Users size={17}/><small>Network</small></button><button onClick={()=>navigate('/jobs')}><BriefcaseBusiness size={17}/><small>Jobs</small></button><button onClick={()=>navigate('/messages')}><MessageSquare size={17}/><small>Inbox</small></button><button onClick={()=>navigate('/profile')}><Code2 size={17}/><small>You</small></button></nav>{notice&&<div className="toast"><Check size={16}/>{notice}<button onClick={()=>setNotice('')}><X size={14}/></button></div>}</div>
}
