import { NavLink, Outlet, useLocation, useNavigate } from 'react-router-dom';
import { Bell, BriefcaseBusiness, Code2, Compass, GitBranch, Home, LogOut, MessageCircle, Moon, Plus, Search, Settings2, Shield, Sun, Users } from 'lucide-react';
import { useAuthStore } from '../features/auth/authStore';
import { useThemeStore } from '../features/theme/themeStore';
import { Button } from '../components/ui/Button';
const primary = [{to:'/home',label:'Home',Icon:Home},{to:'/network',label:'My network',Icon:Users},{to:'/jobs',label:'Jobs',Icon:BriefcaseBusiness},{to:'/projects',label:'Projects',Icon:Code2},{to:'/repositories',label:'Repositories',Icon:GitBranch},{to:'/messages',label:'Messages',Icon:MessageCircle},{to:'/notifications',label:'Notifications',Icon:Bell}];
const secondary = [{to:'/profile',label:'My profile',Icon:Code2},{to:'/search',label:'Discover',Icon:Compass},{to:'/settings',label:'Settings',Icon:Settings2}];
export function AppLayout(){
 const user=useAuthStore(s=>s.user);const signOut=useAuthStore(s=>s.signOut);const toggle=useThemeStore(s=>s.toggleTheme);const theme=useThemeStore(s=>s.theme);const navigate=useNavigate();const location=useLocation();
 const profileDetail=/^\/profile\/[^/]+$/.test(location.pathname)&&!['/profile/me','/profile/create','/profile/edit'].includes(location.pathname);const title=profileDetail?'Community profile':location.pathname==='/profile/edit'?'Edit profile':location.pathname==='/profile/create'?'Create profile':[...primary,...secondary].find(i=>location.pathname===i.to||i.to!=='/profile'&&location.pathname.startsWith(`${i.to}/`))?.label??(location.pathname.startsWith('/profile')?'My profile':'Workspace');
 const link=(items:typeof primary)=>items.map(({to,label,Icon})=><NavLink key={to} to={to} end={to==='/profile'} className={({isActive})=>'workspace-nav-item '+(isActive?'selected':'')}><Icon size={17}/><span>{label}</span>{label==='Notifications'&&<i className="nav-unread"/>}</NavLink>);
 return <div className="workspace-shell"><aside className="workspace-sidebar"><NavLink className="workspace-brand" to="/home"><span className="brand-glyph"><Code2 size={18}/></span><span>linkhub</span><span className="brand-beta">BETA</span></NavLink><NavLink to="/search" className="workspace-search"><Search size={15}/><span>Search LinkHub</span><kbd>⌘ K</kbd></NavLink><div className="workspace-nav-label">WORKSPACE</div><nav className="workspace-nav">{link(primary)}</nav><div className="workspace-nav-label space-between"><span>YOUR SPACE</span><Plus size={13}/></div><nav className="workspace-nav">{link(secondary)}</nav><div className="sidebar-bottom"><button className="workspace-nav-item" onClick={toggle}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}<span>Switch to {theme==='dark'?'light':'dark'}</span></button><button className="workspace-nav-item" onClick={()=>navigate('/admin')}><Shield size={17}/><span>Admin tools</span></button><div className="sidebar-user"><div className="sidebar-avatar">{user?.firstName?.[0]??'S'}</div><div className="sidebar-user-copy"><b>{user ? [user.firstName ?? user.username, user.lastName].filter(Boolean).join(' ') : 'Developer'}</b><small>@{user?.username??'member'}</small></div><button title="Sign out" onClick={()=>{signOut();navigate('/login')}}><LogOut size={15}/></button></div></div></aside><div className="workspace-main"><header className="workspace-topbar"><div className="workspace-breadcrumb"><span>LinkHub</span><i>/</i><b>{title}</b></div><div className="workspace-top-actions"><button className="top-icon" onClick={()=>navigate('/notifications')} aria-label="Notifications"><Bell size={17}/><i/></button><Button variant="primary" size="sm" onClick={()=>navigate('/projects')}><Plus size={14}/> Create</Button><div className="top-avatar">{user?.firstName?.[0]??'S'}</div></div></header><main className="workspace-content"><Outlet/></main></div><nav className="mobile-nav">{[{to:'/home',label:'Home',Icon:Home},{to:'/network',label:'Network',Icon:Users},{to:'/jobs',label:'Jobs',Icon:BriefcaseBusiness},{to:'/messages',label:'Inbox',Icon:MessageCircle},{to:'/profile',label:'You',Icon:Code2}].map(({to,label,Icon})=><NavLink key={to} to={to} end={to==='/profile'} className={({isActive})=>isActive?'active':''}><Icon size={18}/><small>{label}</small></NavLink>)}</nav></div>;
}
