import { type FormEvent, type ReactNode, useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, BriefcaseBusiness, Building2, Check, ChevronDown, Clock3, ExternalLink, FileText, MapPin, Plus, Search, Send, SlidersHorizontal, Users, X } from 'lucide-react';
import api from '../services/api';
import { Button } from '../components/ui/Button';
import { getApiErrorMessage } from '../utils/apiError';
import '../jobs.css';

type Job = { id: number; title: string; description: string; companyName: string; location?: string; salary?: string; jobType: string; skills?: string; active?: boolean; postedById?: number; postedByName?: string; createdAt?: string };
type Application = { id: number; jobId: number; jobTitle: string; applicantId: number; applicantName: string; coverLetter: string; resumeUrl?: string; status: 'PENDING' | 'ACCEPTED' | 'REJECTED'; createdAt?: string };
type Envelope<T> = { data: T; success?: boolean } | T;
type Page<T> = { content?: T[]; totalElements?: number; totalPages?: number } | T[];
const kinds = ['FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', 'FREELANCE'];
const queryKeys = { root: ['jobs'] as const, list: (filters: string[]) => ['jobs', 'list', ...filters] as const, detail: (id: string) => ['jobs', 'detail', id] as const, mine: ['jobs', 'mine'] as const, applications: ['jobs', 'applications', 'mine'] as const, applicants: (id: string) => ['jobs', 'applications', id] as const };
function dataOf<T>(result: Envelope<T>): T { return result && typeof result === 'object' && 'data' in result ? result.data : result as T; }
function rowsOf<T>(result: Envelope<Page<T>>): T[] { const value = dataOf(result); return Array.isArray(value) ? value : value?.content ?? []; }
function dateLabel(value?: string) { if (!value) return 'Recently posted'; const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Recently posted' : new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric' }).format(date); }
function tagsOf(skills?: string) { return (skills ?? '').split(/[,;|]/).map(item => item.trim()).filter(Boolean); }
function titleCase(value: string) { return value.toLowerCase().replace(/\b\w/g, letter => letter.toUpperCase()).replace('_', ' '); }

export function JobsPage() {
  const { id } = useParams();
  const [pathParams] = useSearchParams();
  const view = id === 'recruiter' || pathParams.get('view') === 'recruiter' ? 'recruiter' : id === 'my-applications' ? 'applications' : id ? 'detail' : 'list';
  const navigate = useNavigate(); const client = useQueryClient();
  const [queryInput, setQueryInput] = useState(''); const [query, setQuery] = useState(''); const [locationInput, setLocationInput] = useState(''); const [location, setLocation] = useState(''); const [jobType, setJobType] = useState(''); const [filtersOpen, setFiltersOpen] = useState(true); const [createOpen, setCreateOpen] = useState(false); const [applyOpen, setApplyOpen] = useState(false); const [notice, setNotice] = useState(''); const [errorText, setErrorText] = useState(''); const [selectedJob, setSelectedJob] = useState<number | null>(null);
  useEffect(() => { const timer = window.setTimeout(() => setQuery(queryInput.trim()), 300); return () => window.clearTimeout(timer); }, [queryInput]);
  useEffect(() => { const timer = window.setTimeout(() => setLocation(locationInput.trim()), 300); return () => window.clearTimeout(timer); }, [locationInput]);
  const listQuery = useQuery({ queryKey: queryKeys.list([query, location]), queryFn: async () => {
    const route = query || location ? '/jobs/search' : '/jobs';
    const { data } = await api.get<Envelope<Page<Job>>>(route, { params: { ...(query ? { title: query } : {}), ...(location ? { location } : {}), page: 0, size: 50 } });
    return rowsOf(data);
  }, enabled: view === 'list', staleTime: 30_000 });
  const detailQuery = useQuery({ queryKey: queryKeys.detail(id ?? ''), queryFn: async () => { const { data } = await api.get<Envelope<Job>>(`/jobs/${id}`); return dataOf(data); }, enabled: view === 'detail' && !!id });
  const mineQuery = useQuery({ queryKey: queryKeys.mine, queryFn: async () => { const { data } = await api.get<Envelope<Page<Job>>>('/jobs/me', { params: { page: 0, size: 50 } }); return rowsOf(data); }, enabled: view === 'recruiter' });
  const applicationQuery = useQuery({ queryKey: queryKeys.applications, queryFn: async () => { const { data } = await api.get<Envelope<Page<Application>>>('/jobs/applications/me', { params: { page: 0, size: 50 } }); return rowsOf(data); }, enabled: view === 'applications' });
  const applicantsQuery = useQuery({ queryKey: queryKeys.applicants(String(selectedJob)), queryFn: async () => { const { data } = await api.get<Envelope<Page<Application>>>(`/jobs/${selectedJob}/applications`, { params: { page: 0, size: 50 } }); return rowsOf(data); }, enabled: view === 'recruiter' && selectedJob !== null });
  const visibleJobs = useMemo(() => (listQuery.data ?? []).filter(job => (!jobType || job.jobType === jobType) && (job.active !== false)), [listQuery.data, jobType]);
  const mutationDone = async (message: string) => { setErrorText(''); setNotice(message); window.setTimeout(() => setNotice(''), 4500); await client.invalidateQueries({ queryKey: queryKeys.root }); };
  const createJob = useMutation({ mutationFn: async (body: Record<string, string>) => { const { data } = await api.post<Envelope<Job>>('/jobs', body); return dataOf(data); }, onSuccess: async () => { await mutationDone('Your job listing is live.'); setCreateOpen(false); } });
  const apply = useMutation({ mutationFn: async (body: { coverLetter: string; resumeUrl: string }) => { const { data } = await api.post<Envelope<Application>>(`/jobs/${id}/apply`, body); return dataOf(data); }, onSuccess: async () => { await mutationDone('Application submitted.'); setApplyOpen(false); } });
  const statusUpdate = useMutation({ mutationFn: async ({ applicationId, status }: { applicationId: number; status: string }) => api.patch(`/jobs/applications/${applicationId}/status`, null, { params: { status } }), onSuccess: async () => { await client.invalidateQueries({ queryKey: queryKeys.applicants(String(selectedJob)) }); await mutationDone('Application status updated.'); } });
  const pageError = [listQuery.error, detailQuery.error, mineQuery.error, applicationQuery.error, applicantsQuery.error, createJob.error, apply.error, statusUpdate.error].find(Boolean);
  const setErrorFrom = (error: unknown) => setErrorText(getApiErrorMessage(error, 'The request could not be completed.'));
  const submitCreate = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); createJob.mutate({ title: String(form.get('title')).trim(), description: String(form.get('description')).trim(), companyName: String(form.get('companyName')).trim(), location: String(form.get('location')).trim(), salary: String(form.get('salary')).trim(), jobType: String(form.get('jobType')), skills: String(form.get('skills')).trim() }, { onError: setErrorFrom }); };
  const submitApply = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); apply.mutate({ coverLetter: String(form.get('coverLetter')).trim(), resumeUrl: String(form.get('resumeUrl')).trim() }, { onError: setErrorFrom }); };

  return <main className="workspace-page jobs-page">
    <div className="jobs-heading"><div><div className="page-kicker"><BriefcaseBusiness size={13}/> WORK THAT MOVES YOU</div><h1>{view === 'detail' ? (detailQuery.data?.title ?? 'Job details') : view === 'applications' ? 'My applications' : view === 'recruiter' ? 'Recruiter dashboard' : 'Find your next role'}</h1><p>{view === 'detail' ? 'Get the details and apply when it feels right.' : view === 'applications' ? 'Keep track of the opportunities you’ve applied to.' : view === 'recruiter' ? 'Manage your openings and review applicants.' : 'Discover thoughtful teams looking for people like you.'}</p></div><div className="jobs-heading-actions">{view === 'list' && <Button onClick={() => navigate('/jobs/my-applications')}><FileText size={15}/> My applications</Button>}{view !== 'recruiter' && <Button variant="primary" onClick={() => navigate('/jobs/recruiter')}><Building2 size={15}/> Recruiter dashboard</Button>}{view === 'recruiter' && <Button variant="primary" onClick={() => { setCreateOpen(value => !value); setErrorText(''); }}><Plus size={15}/> Post a job</Button>}</div></div>
    <nav className="jobs-subnav"><Link className={view === 'list' || view === 'detail' ? 'active' : ''} to="/jobs">Explore jobs</Link><Link className={view === 'applications' ? 'active' : ''} to="/jobs/my-applications">My applications</Link><Link className={view === 'recruiter' ? 'active' : ''} to="/jobs/recruiter">Recruiter dashboard</Link></nav>
    {(errorText || pageError) && <div className="jobs-alert" role="alert">{errorText || getApiErrorMessage(pageError, 'Could not load job information. Check that the API is running.')}</div>}
    {notice && <div className="jobs-success" role="status"><Check size={15}/>{notice}<button aria-label="Dismiss" onClick={() => setNotice('')}><X size={14}/></button></div>}
    {view === 'list' && <div className="jobs-browser"><aside className="jobs-filters"><button className="jobs-filter-title" onClick={() => setFiltersOpen(value => !value)}><span><SlidersHorizontal size={15}/> Filter jobs</span><ChevronDown size={14} className={filtersOpen ? '' : 'closed'}/></button>{filtersOpen && <div className="jobs-filter-fields"><label>Keyword<input value={queryInput} onChange={event => setQueryInput(event.target.value)} placeholder="Title or keywords"/></label><label>Location<input value={locationInput} onChange={event => setLocationInput(event.target.value)} placeholder="City or remote"/></label><label>Job type<select value={jobType} onChange={event => setJobType(event.target.value)}><option value="">All job types</option>{kinds.map(kind => <option value={kind} key={kind}>{titleCase(kind)}</option>)}</select></label><button className="jobs-clear" onClick={() => { setQueryInput(''); setLocationInput(''); setJobType(''); }}>Clear filters</button></div>}</aside><section className="jobs-listing"><div className="jobs-results-heading"><div><h2>Open roles</h2><p>{listQuery.data?.length ?? '—'} opportunities from the LinkHub community</p></div><div className="jobs-search-inline"><Search size={14}/><input value={queryInput} onChange={event => setQueryInput(event.target.value)} placeholder="Search jobs" aria-label="Search jobs"/></div></div>{listQuery.isLoading ? <JobLoading/> : listQuery.isError ? <JobsEmpty title="Couldn’t load open roles" detail="Check your connection and try again." action={<Button onClick={() => void listQuery.refetch()}>Try again</Button>}/> : visibleJobs.length === 0 ? <JobsEmpty title={query || location || jobType ? 'No roles match those filters' : 'No open roles yet'} detail={query || location || jobType ? 'Try a different keyword or clear one of the filters.' : 'New opportunities will show up here when teams post them.'}/> : <div className="job-list">{visibleJobs.map(job => <JobCard key={job.id} job={job} onOpen={() => navigate(`/jobs/${job.id}`)}/>)}</div>}</section></div>}
    {view === 'detail' && (detailQuery.isLoading ? <JobLoading/> : detailQuery.isError || !detailQuery.data ? <JobsEmpty title="Job details are unavailable" detail="This role may have closed or the server could not be reached." action={<Button onClick={() => navigate('/jobs')}><ArrowLeft size={14}/> Browse jobs</Button>}/> : <JobDetail job={detailQuery.data} onApply={() => { setErrorText(''); setApplyOpen(true); }} onBack={() => navigate('/jobs')}/>)}
    {view === 'applications' && <section className="jobs-panel">{applicationQuery.isLoading ? <JobLoading/> : applicationQuery.isError ? <JobsEmpty title="Couldn’t load your applications" detail="Check your connection and try again." action={<Button onClick={() => void applicationQuery.refetch()}>Try again</Button>}/> : !(applicationQuery.data?.length) ? <JobsEmpty title="No applications yet" detail="When you apply to a role, you can follow its status here." action={<Button variant="primary" onClick={() => navigate('/jobs')}>Explore jobs <ArrowRight size={14}/></Button>}/> : <div className="application-list">{applicationQuery.data.map(application => <article className="application-card" key={application.id}><div className="application-symbol"><FileText size={18}/></div><div className="application-main"><div className="application-date">Applied {dateLabel(application.createdAt)}</div><h2>{application.jobTitle}</h2><Link to={`/jobs/${application.jobId}`}>View job details <ArrowRight size={13}/></Link></div><StatusPill status={application.status}/></article>)}</div>}</section>}
    {view === 'recruiter' && <section className="recruiter-content">{createOpen && <form className="job-create-form" onSubmit={submitCreate}><div className="form-title"><div><h2>Post a new role</h2><p>Tell people what your team needs.</p></div><button type="button" aria-label="Close" onClick={() => setCreateOpen(false)}><X size={17}/></button></div><div className="job-form-grid"><label>Job title *<input name="title" required maxLength={120} placeholder="Senior Product Engineer"/></label><label>Company *<input name="companyName" required maxLength={120} placeholder="Company name"/></label><label>Location<input name="location" placeholder="Remote, New York…"/></label><label>Salary range<input name="salary" placeholder="$120k–$160k"/></label><label>Job type *<select name="jobType" required defaultValue="FULL_TIME">{kinds.map(kind => <option key={kind} value={kind}>{titleCase(kind)}</option>)}</select></label><label>Skills <span>(comma separated)</span><input name="skills" placeholder="React, TypeScript, APIs"/></label><label className="wide">Description *<textarea name="description" required rows={6} placeholder="Describe the role, team, and what success looks like."/></label></div><div className="job-form-actions"><Button type="button" onClick={() => setCreateOpen(false)}>Cancel</Button><Button type="submit" variant="primary" disabled={createJob.isPending}>{createJob.isPending ? 'Publishing…' : 'Publish role'} <ArrowRight size={14}/></Button></div></form>}
      {mineQuery.isLoading ? <JobLoading/> : mineQuery.isError ? <JobsEmpty title="Couldn’t load your job listings" detail="Check your connection and try again." action={<Button onClick={() => void mineQuery.refetch()}>Try again</Button>}/> : <><div className="recruiter-summary"><div><span>YOUR OPENINGS</span><b>{mineQuery.data?.filter(job => job.active !== false).length ?? 0}</b></div><div><span>TOTAL LISTINGS</span><b>{mineQuery.data?.length ?? 0}</b></div><div><span>APPLICANTS</span><b>{applicantsQuery.data?.length ?? (selectedJob ? '—' : 'Select a role')}</b></div></div>{!mineQuery.data?.length ? <JobsEmpty title="Your recruiting space is ready" detail="Publish a role and review your applicants from this dashboard." action={<Button variant="primary" onClick={() => setCreateOpen(true)}><Plus size={14}/> Post your first role</Button>}/> : <div className="recruiter-grid"><div className="recruiter-job-list"><h2>Your job listings</h2>{mineQuery.data.map(job => <button key={job.id} onClick={() => setSelectedJob(job.id)} className={`recruiter-job-choice ${selectedJob === job.id ? 'selected' : ''}`}><BriefcaseBusiness size={16}/><span><b>{job.title}</b><small>{job.companyName} · {job.active === false ? 'Closed' : 'Active'}</small></span><ArrowRight size={14}/></button>)}</div><div className="recruiter-applicant-panel">{selectedJob === null ? <div className="jobs-state-small"><Users size={20}/><p>Choose one of your listings to review applicants.</p></div> : <><div className="applicants-heading"><div><h2>Applicants</h2><p>{applicantsQuery.data?.length ?? 0} applications for {mineQuery.data.find(job => job.id === selectedJob)?.title}</p></div><select aria-label="Select job" value={selectedJob} onChange={event => setSelectedJob(Number(event.target.value))}>{mineQuery.data.map(job => <option key={job.id} value={job.id}>{job.title}</option>)}</select></div>{applicantsQuery.isLoading ? <JobLoading/> : applicantsQuery.isError ? <JobsEmpty title="Couldn’t load applicants" detail="You may not have access to this listing." action={<Button onClick={() => void applicantsQuery.refetch()}>Try again</Button>}/> : !applicantsQuery.data?.length ? <div className="jobs-state-small"><p>No one has applied to this role yet.</p></div> : <div className="applicant-list">{applicantsQuery.data.map(applicant => <ApplicantCard key={applicant.id} applicant={applicant} busy={statusUpdate.isPending} onStatus={status => statusUpdate.mutate({ applicationId: applicant.id, status }, { onError: setErrorFrom })}/>)}</div>}</>}</div></div>}</>}</section>}
    {applyOpen && <div className="jobs-modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) setApplyOpen(false); }}><form className="apply-modal" onSubmit={submitApply}><div className="form-title"><div><div className="page-kicker">APPLICATION</div><h2>{detailQuery.data?.title}</h2><p>{detailQuery.data?.companyName}</p></div><button type="button" aria-label="Close" onClick={() => setApplyOpen(false)}><X size={18}/></button></div><label>Cover letter *<textarea name="coverLetter" required minLength={10} rows={7} placeholder="Share why this role interests you and what you’d bring to the team."/></label><label>Resume link<input name="resumeUrl" type="url" placeholder="https://…"/></label><div className="job-form-actions"><Button type="button" onClick={() => setApplyOpen(false)}>Cancel</Button><Button type="submit" variant="primary" disabled={apply.isPending}>{apply.isPending ? 'Sending…' : 'Submit application'} <Send size={14}/></Button></div></form></div>}
  </main>;
}

function JobCard({ job, onOpen }: { job: Job; onOpen: () => void }) { return <article className="job-card"><div className="job-company-mark"><Building2 size={19}/></div><div className="job-card-main"><div className="job-card-meta"><span>{job.companyName}</span><span>·</span><span>{dateLabel(job.createdAt)}</span></div><button className="job-card-title" onClick={onOpen}>{job.title}</button><div className="job-card-facts">{job.location && <span><MapPin size={13}/>{job.location}</span>}{job.salary && <span>{job.salary}</span>}<span><Clock3 size={13}/>{titleCase(job.jobType)}</span></div>{tagsOf(job.skills).length > 0 && <div className="job-skill-tags">{tagsOf(job.skills).slice(0, 5).map(tag => <span key={tag}>{tag}</span>)}</div>}</div><Button variant="secondary" size="sm" onClick={onOpen}>View role <ArrowRight size={13}/></Button></article>; }
function JobDetail({ job, onApply, onBack }: { job: Job; onApply: () => void; onBack: () => void }) { return <div className="job-detail-layout"><article className="job-detail-card"><button className="back-link" onClick={onBack}><ArrowLeft size={14}/> All jobs</button><div className="job-detail-company"><div className="job-company-mark large"><Building2 size={22}/></div><div><span>{job.companyName}</span><small>{job.location || 'Location not specified'}</small></div></div><h2>{job.title}</h2><div className="job-card-facts">{job.location && <span><MapPin size={13}/>{job.location}</span>}{job.salary && <span>{job.salary}</span>}<span><Clock3 size={13}/>{titleCase(job.jobType)}</span><span>Posted {dateLabel(job.createdAt)}</span></div><div className="job-detail-divider"/><h3>About the role</h3><p className="job-description">{job.description}</p>{tagsOf(job.skills).length > 0 && <><h3>Skills and technologies</h3><div className="job-skill-tags large-tags">{tagsOf(job.skills).map(tag => <span key={tag}>{tag}</span>)}</div></>}</article><aside className="job-apply-card"><h3>Interested in this role?</h3><p>Send your application directly to the hiring team.</p><Button variant="primary" onClick={onApply}>Apply now <ArrowRight size={14}/></Button><small>You'll need a short cover letter. A resume link is optional.</small></aside></div>; }
function ApplicantCard({ applicant, busy, onStatus }: { applicant: Application; busy: boolean; onStatus: (status: string) => void }) { return <article className="applicant-card"><div className="applicant-avatar">{applicant.applicantName?.split(/\s+/).map(part => part[0]).slice(0, 2).join('') || 'A'}</div><div className="applicant-copy"><div className="applicant-top"><div><h3>{applicant.applicantName || 'Applicant'}</h3><small>Applied {dateLabel(applicant.createdAt)}</small></div><StatusPill status={applicant.status}/></div><p>{applicant.coverLetter}</p>{applicant.resumeUrl && <a href={applicant.resumeUrl} target="_blank" rel="noreferrer"><ExternalLink size={12}/> Resume link</a>}{applicant.status === 'PENDING' && <div className="applicant-actions"><Button size="sm" variant="primary" disabled={busy} onClick={() => onStatus('ACCEPTED')}><Check size={13}/> Accept</Button><Button size="sm" disabled={busy} onClick={() => onStatus('REJECTED')}><X size={13}/> Decline</Button></div>}</div></article>; }
function StatusPill({ status }: { status: string }) { return <span className={`application-status ${status.toLowerCase()}`}>{titleCase(status)}</span>; }
function JobsEmpty({ title, detail, action }: { title: string; detail: string; action?: ReactNode }) { return <div className="jobs-empty"><span><BriefcaseBusiness size={20}/></span><h2>{title}</h2><p>{detail}</p>{action}</div>; }
function JobLoading() { return <div className="jobs-loading" aria-label="Loading jobs"><i/><i/><i/></div>; }
