import { type ChangeEvent, type FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowLeft, Check, File, MessageCircle, MoreHorizontal, Paperclip, Plus, Search, Send, Smile, UserRound, X } from 'lucide-react';
import { useAuthStore } from '../features/auth/authStore';
import api from '../services/api';
import { Button } from '../components/ui/Button';
import { getApiErrorMessage } from '../utils/apiError';
import { useAcceptedConnections } from '../hooks/useConnections';
import { profileService } from '../services/profileService';
import '../messages.css';

type Chat = { id: number; participantIds: number[]; participantNames: string[]; createdAt?: string; updatedAt?: string; lastMessage?: Message | null; unreadCount?: number };
type Message = { id: number; chatId: number; senderId: number; senderName: string; content: string; read?: boolean; createdAt?: string };
type UserRow = { id: number; username: string; firstName?: string; lastName?: string; profilePicture?: string | null; headline?: string | null };
type Envelope<T> = { data: T; success?: boolean } | T;
type Paged<T> = { content?: T[]; totalPages?: number } | T[];
const keys = { chats: ['chats'] as const, messages: (id?: number) => ['chat-messages', id] as const, people: (term: string) => ['chat-people', term] as const };
function valueOf<T>(response: Envelope<T>): T { return response && typeof response === 'object' && 'data' in response ? response.data : response as T; }
function rowsOf<T>(response: Envelope<Paged<T>>): T[] { const value = valueOf(response); return Array.isArray(value) ? value : value?.content ?? []; }
function personName(person: UserRow) { return [person.firstName, person.lastName].filter(Boolean).join(' ') || person.username; }
function initials(name: string) { return name.split(/\s+/).filter(Boolean).slice(0, 2).map(part => part[0]?.toUpperCase()).join('') || '?'; }
function formatTime(value?: string) { if (!value) return ''; const date = new Date(value); if (Number.isNaN(date.getTime())) return ''; return new Intl.DateTimeFormat(undefined, { hour: 'numeric', minute: '2-digit' }).format(date); }
function formatDay(value?: string) { if (!value) return 'Today'; const date = new Date(value); if (Number.isNaN(date.getTime())) return 'Today'; return new Intl.DateTimeFormat(undefined, { weekday: 'long', month: 'long', day: 'numeric' }).format(date); }

export function MessagesPage() {
  const user = useAuthStore(state => state.user); const isDemo = useAuthStore(state => state.isDemo);
  const currentName = user ? [user.firstName, user.lastName].filter(Boolean).join(' ') || user.username : '';
  const myProfile = useQuery({ queryKey: ['profile', 'me'], queryFn: profileService.getMine, enabled: !user?.id && !isDemo, staleTime: 60_000 });
  const viewerId = user?.id ?? myProfile.data?.userId;
  const [urlParams, setUrlParams] = useSearchParams(); const chatParam = urlParams.get('chat'); const activeId = chatParam ? Number(chatParam) : undefined; const recipientParam = urlParams.get('userId');
  const client = useQueryClient(); const [conversationSearch, setConversationSearch] = useState(''); const [messageSearch, setMessageSearch] = useState(''); const [draft, setDraft] = useState(''); const [peopleTerm, setPeopleTerm] = useState(''); const [showNewChat, setShowNewChat] = useState(false); const [emojiOpen, setEmojiOpen] = useState(false); const [stagedFiles, setStagedFiles] = useState<File[]>([]); const [errorMessage, setErrorMessage] = useState(''); const bottomRef = useRef<HTMLDivElement>(null);
  const chats = useQuery({ queryKey: keys.chats, queryFn: async () => { const { data } = await api.get<Envelope<Chat[]>>('/chats'); return valueOf(data) ?? []; }, staleTime: 15_000, refetchInterval: 30_000, enabled: !isDemo });
  const connections = useAcceptedConnections(!isDemo);
  const messages = useQuery({ queryKey: keys.messages(activeId), queryFn: async () => { const path = `/chats/${activeId}/messages`; const first = await api.get<Envelope<Paged<Message>>>(path, { params: { page: 0, size: 50 } }); const firstPage = valueOf(first.data); if (Array.isArray(firstPage)) return firstPage; if ((firstPage.totalPages ?? 1) > 1) { const latest = await api.get<Envelope<Paged<Message>>>(path, { params: { page: (firstPage.totalPages ?? 1) - 1, size: 50 } }); return rowsOf(latest.data); } return firstPage.content ?? []; }, enabled: !isDemo && Number.isFinite(activeId) && Number(activeId) > 0, refetchInterval: 12_000 });
  const people = useQuery({ queryKey: keys.people(peopleTerm), queryFn: async () => { const { data } = await api.get<Envelope<Paged<UserRow>>>('/search/users', { params: { query: peopleTerm, page: 0, size: 12 } }); return rowsOf(data); }, enabled: showNewChat && peopleTerm.trim().length > 0, staleTime: 45_000 });
  const sendMessage = useMutation({ mutationFn: async (content: string) => { const { data } = await api.post<Envelope<Message>>(`/chats/${activeId}/messages`, { content }); return valueOf(data); }, onSuccess: async () => { setDraft(''); setErrorMessage(''); await client.invalidateQueries({ queryKey: keys.messages(activeId) }); await client.invalidateQueries({ queryKey: keys.chats }); } });
  const createChat = useMutation({ mutationFn: async (person: UserRow) => { const { data } = await api.post<Envelope<Chat>>('/chats', { userId: person.id }); return valueOf(data); }, onSuccess: async chat => { await client.invalidateQueries({ queryKey: keys.chats }); setShowNewChat(false); setPeopleTerm(''); setUrlParams({ chat: String(chat.id) }); setErrorMessage(''); } });
  const markRead = useMutation({ mutationFn: () => api.patch(`/chats/${activeId}/messages/read`), onSuccess: () => client.invalidateQueries({ queryKey: keys.messages(activeId) }) });
  const chatRows = chats.data ?? [];
  const activeChat = chatRows.find(chat => chat.id === activeId);
  const otherUserId = (chat: Chat) => chat.participantIds?.find(id => id !== viewerId) ?? chat.participantIds?.[0];
  const otherName = (chat: Chat) => { const index = chat.participantNames?.findIndex((name, i) => chat.participantIds?.[i] !== viewerId && name !== currentName) ?? -1; return chat.participantNames?.[index >= 0 ? index : 0] ?? 'LinkHub member'; };
  const filteredChats = useMemo(() => chatRows.filter(chat => otherName(chat).toLowerCase().includes(conversationSearch.trim().toLowerCase())), [chatRows, conversationSearch, viewerId, currentName]);
  const visibleMessages = useMemo(() => (messages.data ?? []).filter(message => message.content.toLowerCase().includes(messageSearch.trim().toLowerCase())), [messages.data, messageSearch]);
  const connectedUsers = useMemo(() => (connections.data ?? []).map(request => {
    const person = request.sender.userId === viewerId ? request.recipient : request.sender;
    return { id: person.userId, username: person.username, firstName: person.fullName, profilePicture: person.profileImage, headline: person.headline } satisfies UserRow;
  }).filter(person => person.id !== viewerId), [connections.data, viewerId]);
  const connectedIds = useMemo(() => new Set(connectedUsers.map(person => person.id)), [connectedUsers]);
  const visiblePeople = useMemo(() => (people.data ?? []).filter(person => person.id !== viewerId && connectedIds.has(person.id)), [people.data, viewerId, connectedIds]);
  useEffect(() => { if (activeId && messages.data?.length) markRead.mutate(); }, [activeId, messages.data?.length]);
  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth', block: 'end' }); }, [messages.data, activeId]);
  const submit = (event?: FormEvent) => { event?.preventDefault(); const content = draft.trim(); if (!content || !activeId || sendMessage.isPending) return; sendMessage.mutate(content, { onError: error => setErrorMessage(getApiErrorMessage(error, 'Could not send the message.')) }); };
  const choosePerson = (person: UserRow) => { createChat.mutate(person, { onError: error => setErrorMessage(getApiErrorMessage(error, 'Could not start this conversation.')) }); };
  const handledRecipient = useRef<string | null>(null);
  useEffect(() => {
    if (!recipientParam) { handledRecipient.current = null; return; }
    if (isDemo || !connections.isSuccess || !chats.isSuccess || handledRecipient.current === recipientParam) return;
    const id = Number(recipientParam);
    const contact = connectedUsers.find(person => person.id === id);
    if (!contact) { handledRecipient.current = recipientParam; setErrorMessage('You can message this member after they accept your connection request.'); setUrlParams({}); return; }
    const existing = chatRows.find(chat => chat.participantIds?.includes(id));
    if (existing) { handledRecipient.current = recipientParam; setUrlParams({ chat: String(existing.id) }); return; }
    handledRecipient.current = recipientParam;
    choosePerson(contact);
  }, [recipientParam, isDemo, connections.isSuccess, chats.isSuccess, connectedUsers, chatRows]);
  const fileChanged = (event: ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files ?? []); if (files.length) setStagedFiles(current => [...current, ...files].slice(0, 5)); event.target.value = ''; };
  const emojis = ['😊', '🙌', '❤️', '🎉', '😂', '👀', '👍', '✨', '🙏', '🚀', '💡', '🤝'];

  return <div className="workspace-page messages-page">
    <div className="messages-page-heading"><div><div className="page-kicker"><MessageCircle size={13}/> GOOD CONVERSATIONS</div><h1>Messages</h1><p>Keep the collaboration going.</p></div><Button variant="primary" onClick={() => { setShowNewChat(value => !value); setErrorMessage(''); }}><Plus size={15}/> New message</Button></div>
    {errorMessage && <div className="messages-error" role="alert">{errorMessage}<button onClick={() => setErrorMessage('')} aria-label="Dismiss"><X size={14}/></button></div>}
    {isDemo && <div className="messages-demo-note">Messaging is connected to your account API. Sign in with a backend account to load conversations and send messages.</div>}
    <section className="messenger-shell">
      <aside className={`conversation-sidebar ${activeId ? 'has-active' : ''}`}>
        <div className="conversation-sidebar-head"><div><h2>Inbox</h2><span>{chatRows.length} conversations</span></div><button aria-label="Start a new message" onClick={() => setShowNewChat(value => !value)}><Plus size={17}/></button></div>
        <label className="conversation-search"><Search size={14}/><input value={conversationSearch} onChange={event => setConversationSearch(event.target.value)} placeholder="Search conversations" aria-label="Search conversations"/></label>
        {chats.isLoading && !isDemo ? <div className="conversation-loading">Loading conversations…</div> : chats.isError && !isDemo ? <div className="conversation-error">{getApiErrorMessage(chats.error, 'Could not load your conversations.')}<button onClick={() => void chats.refetch()}>Try again</button></div> : <div className="conversation-list">{filteredChats.map(chat => { const name = otherName(chat); return <div key={chat.id} className={`conversation-row ${activeId === chat.id ? 'active' : ''}`} onClick={() => setUrlParams({ chat: String(chat.id) })} role="button" tabIndex={0} onKeyDown={event=>{if(event.key==='Enter')setUrlParams({chat:String(chat.id)});}}>{otherUserId(chat) ? <Link className="conversation-avatar" to={`/profile/${otherUserId(chat)}`} onClick={event=>event.stopPropagation()}>{initials(name)}</Link> : <span className="conversation-avatar">{initials(name)}</span>}<span className="conversation-info"><Link className="conversation-profile-link" to={otherUserId(chat) ? `/profile/${otherUserId(chat)}` : '#'} onClick={event=>event.stopPropagation()}>{name}</Link><small>{chat.lastMessage?.content ?? (chat.updatedAt ? `Updated ${formatDay(chat.updatedAt)}` : 'Start a conversation')}</small></span><span className="conversation-row-meta"><span className="conversation-time">{formatTime(chat.lastMessage?.createdAt ?? chat.updatedAt)}</span>{!!chat.unreadCount && <span className="conversation-unread">{chat.unreadCount}</span>}</span></div>; })}{!filteredChats.length && <div className="conversation-empty">{conversationSearch ? 'No conversations match that search.' : 'Your conversations will appear here.'}</div>}
          <div className="connected-people-heading"><b>Connected people</b><span>{connectedUsers.length}</span></div>
          {connections.isLoading && <div className="conversation-loading">Loading connections…</div>}
          {connections.isError && <div className="conversation-error">{getApiErrorMessage(connections.error, 'Could not load your connections.')}</div>}
          {!connections.isLoading && !connections.isError && connectedUsers.map(person => <div key={`contact-${person.id}`} className="conversation-row contact-row"><Link className="conversation-avatar" to={`/profile/${person.id}`}>{person.profilePicture ? <img src={person.profilePicture} alt=""/> : initials(personName(person))}</Link><Link className="conversation-info conversation-profile-link-wrap" to={`/profile/${person.id}`}><b>{personName(person)}</b><small>@{person.username} · Connected</small></Link><button className="contact-message-action" onClick={() => choosePerson(person)} disabled={createChat.isPending}>Message</button></div>)}
        </div>}
      </aside>
      <section className={`chat-window ${activeId ? 'chat-selected' : ''}`}>
        {activeChat ? <>
          <header className="chat-header"><button className="chat-back" onClick={() => setUrlParams({})} aria-label="Back to conversations"><ArrowLeft size={17}/></button>{otherUserId(activeChat) ? <Link className="conversation-avatar" to={`/profile/${otherUserId(activeChat)}`}>{initials(otherName(activeChat))}</Link> : <span className="conversation-avatar">{initials(otherName(activeChat))}</span>}<div className="chat-header-copy"><b>{otherUserId(activeChat) ? <Link to={`/profile/${otherUserId(activeChat)}`}>{otherName(activeChat)}</Link> : otherName(activeChat)}</b><small>LinkHub conversation</small></div><div className="chat-header-actions"><label className="message-search"><Search size={14}/><input value={messageSearch} onChange={event => setMessageSearch(event.target.value)} placeholder="Search messages" aria-label="Search messages"/><button aria-label="Clear message search" onClick={() => setMessageSearch('')}><X size={12}/></button></label><button aria-label="More conversation options" className="chat-more"><MoreHorizontal size={18}/></button></div></header>
          <div className="message-history" aria-live="polite">{messages.isLoading ? <div className="message-loading">Loading messages…</div> : messages.isError ? <div className="message-load-error">{getApiErrorMessage(messages.error, 'Could not load this conversation.')}<button onClick={() => void messages.refetch()}>Retry</button></div> : visibleMessages.length ? <>{visibleMessages.map((message, index) => { const own = message.senderId === user?.id || (message.senderName && message.senderName === currentName); const previous = visibleMessages[index - 1]; const showDay = !previous || formatDay(previous.createdAt) !== formatDay(message.createdAt); return <div key={message.id}>{showDay && <div className="message-day-divider"><span>{formatDay(message.createdAt)}</span></div>}<article className={`message-row ${own ? 'own' : ''}`}><span className="message-avatar">{initials(message.senderName || (own ? currentName : otherName(activeChat)))}</span><div className="message-bubble-wrap"><div className="message-author-line"><b>{own ? 'You' : message.senderName}</b><time>{formatTime(message.createdAt)}</time></div><div className="message-bubble">{message.content}</div></div>{own && message.read && <Check size={12} className="message-read" aria-label="Read"/>}</article></div>; })}<div ref={bottomRef}/></> : <div className="chat-empty"><span><MessageCircle size={22}/></span><h3>{messageSearch ? 'No matching messages' : 'Say hello'}</h3><p>{messageSearch ? 'Try another word or phrase.' : `Your conversation with ${otherName(activeChat)} starts here.`}</p></div>}</div>
          {stagedFiles.length > 0 && <div className="staged-attachments">{stagedFiles.map((file, index) => <span key={`${file.name}-${index}`}><File size={13}/>{file.name}<button aria-label={`Remove ${file.name}`} onClick={() => setStagedFiles(current => current.filter((_, fileIndex) => fileIndex !== index))}><X size={12}/></button></span>)}<small>Attachments are selected locally; this chat API currently accepts text only.</small></div>}
          <form className="message-composer" onSubmit={submit}><div className="composer-tools"><label title="Attach file" className="attach-button"><Paperclip size={16}/><input type="file" multiple onChange={fileChanged} aria-label="Choose attachments"/></label><div className="emoji-wrap"><button type="button" aria-label="Choose emoji" onClick={() => setEmojiOpen(value => !value)}><Smile size={16}/></button>{emojiOpen && <div className="emoji-picker" role="listbox" aria-label="Emoji">{emojis.map(emoji => <button key={emoji} type="button" onClick={() => { setDraft(value => value + emoji); setEmojiOpen(false); }}>{emoji}</button>)}</div>}</div></div><textarea value={draft} onChange={event => setDraft(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); submit(); } }} placeholder="Write a message…" aria-label="Write a message" rows={1}/><button className="send-message" type="submit" disabled={!draft.trim() || sendMessage.isPending} aria-label="Send message">{sendMessage.isPending ? <span className="send-spinner"/> : <Send size={16}/>}</button></form><div className="composer-hint">Enter to send · Shift + Enter for a new line</div>
        </> : <div className="no-chat-selected"><span><MessageCircle size={24}/></span><h2>Your inbox, your people.</h2><p>Select a conversation or start a new message to keep the conversation going.</p><Button variant="primary" onClick={() => setShowNewChat(true)}><Plus size={14}/> New message</Button></div>}
      </section>
    </section>
    {showNewChat && <div className="new-chat-overlay" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) setShowNewChat(false); }}><section className="new-chat-modal" role="dialog" aria-modal="true" aria-labelledby="new-chat-title"><header><div><div className="page-kicker">START A CONVERSATION</div><h2 id="new-chat-title">New message</h2></div><button aria-label="Close" onClick={() => setShowNewChat(false)}><X size={17}/></button></header><label className="new-chat-search"><Search size={15}/><input autoFocus value={peopleTerm} onChange={event => setPeopleTerm(event.target.value)} placeholder="Find a LinkHub member" aria-label="Find a LinkHub member"/></label><div className="new-chat-results">{people.isFetching && <p className="new-chat-state">Looking for people…</p>}{people.isError && <p className="new-chat-state error">{getApiErrorMessage(people.error, 'Member search failed.')}</p>}{peopleTerm.trim() && people.isSuccess && visiblePeople.map(person => <button key={person.id} className="new-chat-person" onClick={() => choosePerson(person)} disabled={createChat.isPending}><span className="conversation-avatar">{person.profilePicture ? <img src={person.profilePicture} alt=""/> : initials(personName(person))}</span><span><b>{personName(person)}</b><small>@{person.username}{person.headline ? ` · ${person.headline}` : ''}</small></span><ArrowLeft className="new-chat-arrow" size={15}/></button>)}{peopleTerm.trim() && people.isSuccess && !visiblePeople.length && <p className="new-chat-state">No members found for that search.</p>}{!peopleTerm.trim() && <p className="new-chat-state"><UserRound size={16}/> Search for someone by name or username.</p>}</div></section></div>}
  </div>;
}
